apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: cotisations
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
  namespace: cotisations
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "services", "pods", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-rolebinding
  namespace: cotisations
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: cotisations
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io